In [1]:
import os

from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
# Change current working dir
print("Original working dir: ", os.getcwd())
os.chdir(os.path.join(os.getcwd(), "us-mutual-funds-and-etfs-analysis"))
print("New working dir: ", os.getcwd())

Original working dir:  D:\Projects\Python
New working dir:  D:\Projects\Python\us-mutual-funds-and-etfs-analysis

In [3]:
# Load dataset
df = pd.read_csv('dataset/ETFs.csv')

# Basic info
df['count'] = 1

for column in df.columns:
    print(df.groupby(column).count()['count'])
    print()

analysis_columns = [
    'category',
    'fund_family',
    'investment',
    'size',
    'currency',
]
for i, column in analysis_columns:     
    # Aggregate
    sub_df = df.groupby(column).count()['count']
    
    # Plot
    sub_df.plot.bar()
    plt.show()
    print()
# print(df.describe())

fund_name
1305    1
1306    1
1308    1
1309    1
1310    1
       ..
ZBIO    1
ZIV     1
ZMLP    1
ZROZ    1
ZSL     1
Name: count, Length: 2352, dtype: int64

fund_extended_name
AAM S&P 500 High Dividend Value ETF                 1
AAM S&P Emerging Markets High Dividend Value ETF    1
ABF Pan Asia Bond Index                             1
AGFiQ Hedged Dividend Income Fund                   1
AGFiQ U.S. Market Neutral Anti-Beta Fund            1
                                                   ..
iShares € Govt Bond 5-7yr ETF EUR Dist              1
iShares € Govt Bond 7-10yr ETF EUR Acc              1
iShares € Govt Bond 7-10yr ETF EUR Dist             1
iShares € Inflat Lnkd GovtBd ETF EUR Acc            1
iShares € Ultrashort Bond ETF EUR Dist              1
Name: count, Length: 2340, dtype: int64

category
Allocation - 15% to 30% Equity     5
Allocation - 30% to 50% Equity    10
Allocation - 50% to 70% Equity     8
Allocation - 70% to 85% Equity     4
Allocation - 85%+ Equity           3
                                  ..
Utilities                         10
Volatility                        10
World Allocation                   7
World Bond                         8
World Stock                       34
Name: count, Length: 95, dtype: int64

fund_family
AAM                   2
ABSA Capital ETF     10
AGFiQ                 5
ALPS                 18
ALPS ETF              1
                   ...
WBI Investments      12
WisdomTree           82
YieldShares           1
iShares             339
weatherstorm          1
Name: count, Length: 174, dtype: int64

net_assets
1.967800e+05    1
2.581800e+05    1
3.424300e+05    1
4.382300e+05    1
4.627400e+05    1
               ..
3.730000e+12    1
4.010000e+12    1
5.970000e+12    1
6.450000e+12    1
8.430000e+12    1
Name: count, Length: 2127, dtype: int64

ytd_return
-73.09     1
-68.13     1
-65.75     1
-65.62     1
-65.37     1
          ..
 122.17    1
 123.17    1
 138.38    1
 139.60    1
 161.53    1
Name: count, Length: 1578, dtype: int64

fund_yield
0.00     350
0.01       2
0.02       1
0.03       2
0.04       2
        ...
17.56      1
19.44      1
21.17      1
21.70      2
22.71      1
Name: count, Length: 579, dtype: int64

legal_type
Exchange Traded Fund    2352
Name: count, dtype: int64

investment
Blend     759
Growth    379
Value     524
Name: count, dtype: int64

size
Large     1105
Medium     394
Small      163
Name: count, dtype: int64

currency
EUR       2
GBP       5
USD    2345
Name: count, dtype: int64

net_annual_expense_ratio_fund
0.00    155
0.02      1
0.03      8
0.04     17
0.05     10
       ...
2.78      1
2.96      1
3.48      1
3.50      1
9.41      1
Name: count, Length: 161, dtype: int64

net_annual_expense_ratio_category
0.00     1
0.11    10
0.13     9
0.14     8
0.16    12
        ..
0.95    21
1.05     9
1.06     1
1.12    15
1.19    18
Name: count, Length: 61, dtype: int64

portfolio_stocks
0.00      705
0.02        2
0.03        4
0.04        1
0.05        1
         ...
99.96      19
99.97      16
99.98      13
99.99      15
100.00    136
Name: count, Length: 486, dtype: int64

portfolio_bonds
0.00      1825
0.01         9
0.02         2
0.03         1
0.04         1
          ...
99.96        1
99.97        2
99.98        2
99.99        3
100.00      20
Name: count, Length: 432, dtype: int64

price_earnings
0.00     741
4.15       1
4.44       1
4.95       1
5.03       1
        ...
43.56      1
43.77      1
43.79      1
45.09      1
49.27      1
Name: count, Length: 956, dtype: int64

price_book
0.00     743
0.33       1
0.47       1
0.48       5
0.50       2
        ...
7.47       1
7.59       1
7.64       1
9.31       1
10.77      1
Name: count, Length: 384, dtype: int64

price_sales
0.00     741
0.19       2
0.24       1
0.30       1
0.31       1
        ...
8.36       1
9.96       1
10.01      2
10.02      1
10.15      1
Name: count, Length: 368, dtype: int64

price_cashflow
0.00     742
0.47       6
0.62       1
0.85       1
0.90       3
        ...
25.59      1
26.10      1
26.59      1
33.85      1
41.98      1
Name: count, Length: 836, dtype: int64

basic_materials
0.00      1078
0.01         2
0.02         3
0.03         2
0.04         2
          ...
97.60        1
98.21        2
98.36        1
99.48        1
100.00      13
Name: count, Length: 835, dtype: int64

consumer_cyclical
0.00     1036
0.01        1
0.02        1
0.03        1
0.06        3
         ...
93.44       1
94.76       1
97.50       1
97.59       1
99.39       1
Name: count, Length: 942, dtype: int64

financial_services
0.00      1113
0.03         2
0.07         1
0.08         1
0.09         1
          ...
99.87        1
99.92        1
99.94        1
99.99        1
100.00      27
Name: count, Length: 968, dtype: int64

real_estate
0.00      1255
0.01         3
0.02         2
0.03         1
0.04         1
          ...
99.58        1
99.67        1
99.69        1
99.83        1
100.00      25
Name: count, Length: 708, dtype: int64

consumer_defensive
0.00      1175
0.01         3
0.05         2
0.06         1
0.07         1
          ...
98.96        1
99.14        1
99.60        1
99.82        1
100.00       3
Name: count, Length: 815, dtype: int64

healthcare
0.00      1185
0.01         1
0.02         1
0.07         1
0.11         1
          ...
99.52        1
99.71        2
99.79        1
99.98        3
100.00      19
Name: count, Length: 860, dtype: int64

utilities
0.00      1274
0.01         3
0.02         2
0.03         1
0.05         1
          ...
98.95        1
99.02        2
99.45        1
99.49        1
100.00       4
Name: count, Length: 669, dtype: int64

communication_services
0.00     1221
0.01        1
0.02        1
0.03        1
0.04        1
         ...
39.21       1
41.53       1
41.54       1
41.80       1
99.37       1
Name: count, Length: 634, dtype: int64

energy
0.00      1195
0.01         2
0.02         2
0.03         1
0.04         2
          ...
99.12        1
99.13        1
99.15        1
99.51        2
100.00      16
Name: count, Length: 764, dtype: int64

industrials
0.00      967
0.01        3
0.02        1
0.04        4
0.05        1
         ...
93.03       1
93.70       1
96.27       2
96.69       1
100.00      5
Name: count, Length: 1012, dtype: int64

technology
0.00      1067
0.01         4
0.02         1
0.06         2
0.14         2
          ...
98.64        1
99.23        1
99.68        1
99.75        1
100.00       6
Name: count, Length: 1022, dtype: int64

rating_us_government
0.0    2348
Name: count, dtype: int64

rating_aaa
-0.67       1
-0.38       1
-0.05       1
-0.03       1
-0.02       1
           ..
 99.29      1
 99.71      1
 99.86      1
 99.95      1
 100.00    48
Name: count, Length: 223, dtype: int64

rating_aa
0.00      2141
0.05         1
0.32         1
0.44         1
0.45         1
          ...
72.61        1
74.20        1
76.22        1
99.90        1
100.00       1
Name: count, Length: 200, dtype: int64

rating_a
0.00     2137
0.07        1
0.14        1
0.91        1
0.98        2
         ...
52.56       1
55.27       1
58.27       1
58.77       1
77.00       1
Name: count, Length: 207, dtype: int64

rating_bbb
0.00     2108
0.01        1
0.05        1
0.07        2
0.14        1
         ...
60.23       1
61.59       1
64.94       1
73.75       1
80.56       1
Name: count, Length: 231, dtype: int64

rating_bb
0.00     2212
0.03        1
0.05        1
0.07        1
0.10        1
         ...
60.55       1
60.86       1
70.32       1
70.49       1
73.25       1
Name: count, Length: 130, dtype: int64

rating_b
0.00      2235
0.03         2
0.10         1
0.14         1
0.31         1
          ...
57.79        1
58.91        1
59.76        1
67.61        1
100.00       1
Name: count, Length: 110, dtype: int64

rating_below_b
0.00     2244
0.01        3
0.07        1
0.08        2
0.09        1
         ...
18.17       1
18.77       1
26.10       1
38.83       1
58.96       1
Name: count, Length: 97, dtype: int64

rating_others
0.00      2223
0.01         4
0.02         1
0.03         5
0.04         2
          ...
37.82        1
38.66        1
47.14        1
60.99        1
100.00       1
Name: count, Length: 98, dtype: int64

fund_return_ytd
-63.12     1
-58.14     1
-57.97     1
-57.46     1
-57.43     1
          ..
 82.55     1
 100.22    1
 100.90    1
 102.20    1
 103.15    1
Name: count, Length: 1661, dtype: int64

category_return_ytd
-4.75      1
-3.80     34
-2.36     19
-2.26      4
-0.81      1
          ..
 15.40    21
 20.41    30
 25.03    22
 61.57     6
 88.20    11
Name: count, Length: 80, dtype: int64

fund_return_1month
-26.63    1
-23.52    1
-22.68    1
-22.59    1
-17.69    1
         ..
 15.22    1
 17.00    1
 24.10    1
 25.36    1
 28.86    1
Name: count, Length: 953, dtype: int64

category_return_1month
-6.17    15
-5.94    11
-4.64    11
-4.33    23
-4.12    35
         ..
 2.55     7
 3.09    21
 3.36    19
 4.48    18
 9.76     6
Name: count, Length: 77, dtype: int64

fund_return_3months
-63.12     1
-58.14     1
-57.97     1
-57.46     1
-57.43     1
          ..
 82.55     1
 100.22    1
 100.90    1
 102.20    1
 103.15    1
Name: count, Length: 1668, dtype: int64

category_return_3months
-14.96    11
-6.47     11
-5.42     18
-5.19     10
-4.30     15
          ..
 6.80     34
 7.04     69
 7.19     32
 8.24      7
 9.72      6
Name: count, Length: 82, dtype: int64

fund_return_1year
-80.57    1
-72.24    1
-58.91    1
-58.01    1
-55.01    1
         ..
 44.20    1
 49.40    1
 53.99    1
 55.13    1
 77.62    1
Name: count, Length: 1680, dtype: int64

category_return_1year
-17.63    18
-16.00     1
-4.15     21
-3.67     22
-2.23     23
          ..
 18.43    22
 19.51    23
 22.79    30
 49.47     6
 68.50    11
Name: count, Length: 81, dtype: int64

fund_return_3years
-86.64    1
-84.09    1
-67.38    1
-67.28    1
-65.79    1
         ..
 42.46    1
 42.95    1
 45.38    1
 49.25    1
 52.40    1
Name: count, Length: 1300, dtype: int64

category_return_3years
-26.81    18
-15.94    21
-13.55    23
-12.53     1
-8.38     18
          ..
 11.46    45
 12.67    34
 12.72     9
 12.81    23
 13.17    48
Name: count, Length: 80, dtype: int64

fund_return_5years
-82.83    1
-80.82    1
-79.09    1
-74.96    1
-71.13    1
         ..
 29.51    1
 30.93    1
 33.36    1
 40.85    1
 42.34    1
Name: count, Length: 1080, dtype: int64

category_return_5years
-19.71      1
-17.55     18
-16.70     11
-10.68     21
-8.87      18
         ...
 15.76    114
 15.92     41
 17.05     45
 17.24     22
 20.22     34
Name: count, Length: 79, dtype: int64

fund_return_10years
-52.57    1
-51.31    1
-50.92    1
-47.66    1
-44.72    1
         ..
 36.79    1
 39.00    1
 39.58    1
 40.74    1
 48.41    1
Name: count, Length: 629, dtype: int64

category_return_10years
-16.57      18
-7.74       21
-3.63       11
-0.40       32
 0.00     1217
 0.74       15
 1.17       35
 1.18       23
 1.23       31
 1.68       19
 1.76       51
 1.96        5
 2.14        9
 2.43       15
 2.51        6
 2.52       34
 2.78        3
 3.48        7
 3.59       69
 3.69       30
 4.34       12
 4.65       15
 4.67       11
 5.52       23
 5.74       21
 5.86        6
 6.03       20
 6.08       22
 6.10       35
 6.20       31
 6.55       81
 6.63       10
 6.83       22
 7.03        8
 7.28       15
 7.33      114
 7.35       22
 7.39       21
 7.88       41
 8.16       25
 8.68       48
 9.48       45
 9.55       14
 12.26      34
Name: count, dtype: int64

fund_return_2018
-91.68     1
-79.74     1
-77.58     1
-74.27     1
-73.87     1
          ..
 50.99     1
 53.82     1
 57.61     1
 66.72     1
 125.71    1
Name: count, Length: 1463, dtype: int64

fund_return_2017
-94.06     1
-94.02     1
-83.97     1
-75.63     1
-73.05     1
          ..
 160.63    1
 167.97    1
 171.16    1
 179.12    1
 270.43    1
Name: count, Length: 1628, dtype: int64

fund_return_2016
-97.61     1
-94.12     1
-93.87     1
-93.81     1
-89.33     1
          ..
 111.92    1
 126.23    1
 127.85    1
 139.88    1
 168.34    1
Name: count, Length: 1442, dtype: int64

fund_return_2015
-97.09    1
-87.07    1
-86.92    1
-78.09    1
-77.68    1
         ..
 66.27    1
 70.82    1
 78.39    1
 94.58    1
 98.73    1
Name: count, Length: 1273, dtype: int64

fund_return_2014
-91.15     1
-87.43     1
-83.97     1
-81.83     1
-74.24     1
          ..
 100.82    1
 108.42    1
 130.12    1
 145.78    1
 153.98    1
Name: count, Length: 1222, dtype: int64

fund_return_2013
-95.01     1
-91.69     1
-91.67     1
-82.55     1
-71.49     1
          ..
 151.23    1
 160.14    1
 162.39    1
 181.35    1
 215.14    1
Name: count, Length: 1170, dtype: int64

fund_return_2012
-97.29     1
-97.28     1
-78.11     1
-72.98     1
-61.75     1
          ..
 81.46     1
 81.78     1
 85.16     1
 88.95     1
 155.84    1
Name: count, Length: 980, dtype: int64

fund_return_2011
-67.97     1
-67.46     1
-63.57     1
-63.28     1
-62.69     1
          ..
 50.22     1
 55.81     1
 59.77     1
 71.95     1
 105.41    1
Name: count, Length: 896, dtype: int64

fund_return_2010
-78.79     1
-71.77     1
-68.00     1
-61.98     1
-60.00     1
          ..
 79.44     1
 79.75     1
 79.78     1
 81.95     1
 173.63    1
Name: count, Length: 786, dtype: int64

fund_alpha_3years
-65.68    1
-57.86    1
-51.41    1
-48.92    1
-47.02    1
         ..
 32.65    1
 37.10    1
 41.70    1
 49.72    1
 53.17    1
Name: count, Length: 1032, dtype: int64

category_alpha_3years
-16.86    23
-10.54    21
-8.60      3
-7.11     30
-6.08     15
          ..
 8.52     34
 9.42     10
 9.46     48
 10.06    23
 14.89     9
Name: count, Length: 76, dtype: int64

fund_alpha_5years
-135.99    1
-53.87     1
-52.42     1
-44.76     1
-38.64     1
          ..
 19.63     1
 24.22     1
 24.47     1
 28.65     1
 31.33     1
Name: count, Length: 898, dtype: int64

category_alpha_5years
-18.32    11
-14.03    23
-9.35     30
-8.91      6
-8.22     15
          ..
 6.70     19
 7.21     10
 7.76     23
 7.85     14
 10.91    34
Name: count, Length: 77, dtype: int64

fund_alpha_10years
-34.94    1
-34.58    1
-27.17    1
-24.26    1
-23.36    1
         ..
 13.35    1
 13.80    1
 14.69    1
 15.31    1
 17.00    1
Name: count, Length: 566, dtype: int64

category_alpha_10years
-10.41     18
-4.82      21
-4.45       3
-3.71      32
-3.31       8
-2.21      12
-1.85      20
-1.48      21
-1.12      35
-1.08      23
-0.90      35
-0.65      32
-0.34      81
-0.30      51
-0.18      15
-0.04      30
 0.03      22
 0.13      41
 0.15     114
 0.16      15
 0.41      15
 0.43      34
 0.48      14
 0.53      19
 0.64      25
 0.89      11
 1.92       7
 1.99      45
 2.04      69
 2.36       6
 2.68      23
 3.05       6
 3.29      22
 3.33      11
 3.86      21
 4.22      10
 4.81      15
 5.19      48
 5.72      31
 6.61      14
 9.01      34
 10.03     22
Name: count, dtype: int64

fund_beta_3years
-21.13    1
-18.59    1
-15.89    1
-13.19    1
-12.16    1
         ..
 15.78    1
 19.08    1
 20.93    1
 30.49    1
 90.56    1
Name: count, Length: 368, dtype: int64

category_beta_3years
-1.18       1
-0.40      12
 0.02      19
 0.14       5
 0.22      18
 0.28      10
 0.30      20
 0.32      22
 0.33      10
 0.34      29
 0.48       8
 0.50      11
 0.53      23
 0.54       7
 0.60      30
 0.64      14
 0.65       9
 0.73      12
 0.74      13
 0.76      19
 0.79      10
 0.84      17
 0.87       7
 0.88      22
 0.89      21
 0.91     147
 0.92      34
 0.94      24
 0.95      32
 0.96      26
 0.98     135
 0.99      22
 1.00      11
 1.01      51
 1.02       8
 1.03      85
 1.04      41
 1.05      50
 1.06      56
 1.09       7
 1.10     118
 1.11      15
 1.12      15
 1.15      20
 1.16      12
 1.26      34
 1.30      21
 1.32      30
 1.43      23
 1.49       4
 1.50      18
 1.54       6
 1.57       3
 1.65       6
 2.40       5
 3.65       8
 19.29     15
Name: count, dtype: int64

fund_beta_5years
-22.33    1
-19.53    1
-11.76    1
-11.14    1
-10.87    1
         ..
 20.28    1
 21.80    1
 23.58    1
 24.68    1
 91.39    1
Name: count, Length: 343, dtype: int64

category_beta_5years
-1.22       1
 0.02      19
 0.13       9
 0.14       9
 0.22       5
 0.26       6
 0.32      24
 0.37      10
 0.49      12
 0.52      29
 0.53       7
 0.57       7
 0.58      31
 0.59      14
 0.62      23
 0.66      23
 0.73      10
 0.74       8
 0.77      19
 0.80       8
 0.81       6
 0.83      34
 0.86      11
 0.87      34
 0.88      10
 0.90      81
 0.92      22
 0.93      18
 0.94      57
 0.95      56
 0.96      22
 0.98      11
 0.99      64
 1.00     154
 1.01      23
 1.02      35
 1.04      35
 1.05      93
 1.09      69
 1.10      50
 1.12      93
 1.13       1
 1.14       3
 1.16       1
 1.17       8
 1.31       4
 1.33      30
 1.34      23
 1.35      39
 1.38       6
 1.43       3
 1.46      20
 1.47       3
 1.49      12
 1.66       6
 2.55       5
 3.53       8
 27.98     15
Name: count, dtype: int64

fund_beta_10years
-43.77    1
-43.55    1
-22.79    1
-22.34    1
-6.65     1
         ..
 40.07    1
 44.02    1
 45.18    1
 46.28    1
 52.12    1
Name: count, Length: 210, dtype: int64

category_beta_10years
-7.68     15
 0.21      9
 0.48     10
 0.57     14
 0.60     19
 0.64     22
 0.66     11
 0.73     34
 0.82     15
 0.84      6
 0.85     34
 0.88      5
 0.95     22
 0.96     58
 0.97     81
 0.98     35
 1.00    114
 1.01     36
 1.04     93
 1.06     21
 1.07     43
 1.08     22
 1.09     31
 1.10     48
 1.12     32
 1.14     41
 1.17     15
 1.18     69
 1.20     23
 1.21     35
 1.26     21
 1.28     30
 1.32      6
 1.45     18
 1.49     12
 1.63      3
 1.82     20
 2.52      8
Name: count, dtype: int64

fund_mean_annual_return_3years
-11.84    1
-11.41    1
-7.39     1
-6.19     1
-5.12     1
         ..
 3.74     1
 4.16     1
 4.36     1
 4.91     1
 5.02     1
Name: count, Length: 370, dtype: int64

category_mean_annual_return_3years
-2.06    18
-1.34    21
-1.02     1
-0.96    23
-0.55    18
         ..
 0.97    45
 1.09    23
 1.13    48
 1.14    34
 1.18     9
Name: count, Length: 67, dtype: int64

fund_mean_annual_return_5years
-8.64    1
-8.39    1
-7.45    1
-5.97    1
-5.88    1
        ..
 3.02    1
 3.39    1
 3.70    1
 3.76    1
 4.62    1
Name: count, Length: 335, dtype: int64

category_mean_annual_return_5years
-1.70     1
-1.19    18
-0.84    11
-0.83    21
-0.60    18
         ..
 1.31    41
 1.32    32
 1.38    45
 1.40    22
 1.67    34
Name: count, Length: 62, dtype: int64

fund_mean_annual_return_10years
-5.06    1
-4.94    1
-4.68    1
-4.46    1
-4.27    1
        ..
 3.35    1
 3.52    1
 3.56    1
 3.71    1
 4.27    1
Name: count, Length: 264, dtype: int64

category_mean_annual_return_10years
-0.98     18
-0.46     21
 0.11     15
 0.18      9
 0.22     32
 0.24     19
 0.25     35
 0.30     88
 0.32     15
 0.33     34
 0.36      3
 0.37     12
 0.38     26
 0.42     23
 0.44      7
 0.51     20
 0.55     69
 0.58     11
 0.59     30
 0.61      6
 0.62     24
 0.64     81
 0.67     56
 0.69    136
 0.73     22
 0.74     23
 0.75     15
 0.76     21
 0.78     41
 0.79     31
 0.80     25
 0.83     36
 0.88     93
 1.12     34
Name: count, dtype: int64

fund_r_squared_3years
0.00      462
0.01        4
0.02        1
0.04        2
0.06        1
         ...
99.96       6
99.97       6
99.98       9
99.99       9
100.00     22
Name: count, Length: 1529, dtype: int64

category_r_squared_3years
2.26      12
2.38       5
3.49      15
3.69      29
7.78      22
        ...
93.17     35
94.06    114
95.72     10
97.27      1
97.76      1
Name: count, Length: 78, dtype: int64

fund_r_squared_5years
0.00      748
0.01        3
0.02        1
0.04        2
0.05        1
         ...
99.95       3
99.96       2
99.97       6
99.99      12
100.00     18
Name: count, Length: 1223, dtype: int64

category_r_squared_5years
2.51      5
2.92     19
5.28     15
6.57     29
8.96      9

KeyError: 'count'

In [ ]:
# Analysis
sns.pairplot(df, kind="scatter", palette="Set2")
plt.show()

In [ ]:
print("Finished")